# For more information: https://laravel.com/docs/sail
version: '3.8'

networks:
    nginx_network:
        external: true
    internal:

volumes:
    app-database:
        driver: local
    internal-redis:
        driver: local

services:
    app:
        image: adhocore/phpfpm:8.1
        container_name: app
        working_dir: /app
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - '.:/app'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        links:
            - mysql
        depends_on:
            - mysql
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always
        working_dir: /app
        networks:
            - internal
        ports:
            - "9021:80"
        volumes:
            - .:/app
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
    app-composer:
        image: composer:latest
        container_name: app-composer
        working_dir: /app
        command: update --ignore-platform-reqs
        volumes:
            - .:/app
        restart: on-failure
        depends_on:
            - app
    mysql:
        # image: 'mysql/mysql-server:8.0'
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        # environment:
        #     MYSQL_ROOT_PASSWORD: 'password'
        #     MYSQL_ROOT_HOST: "%"
        #     MYSQL_DATABASE: 'app'
        #     MYSQL_USER: 'root'
        #     MYSQL_PASSWORD: 'password'
        #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
        # volumes:
        #     - .:/app
        #     - ./app-database:/var/lib/postgresql/data
        # networks:
        #     - internal
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        #     retries: 3
        #     timeout: 5s
        image: mariadb:latest
        restart: always
        container_name: database
        working_dir: /app
        networks:
            - internal
            - nginx_network
        command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=app
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/app
            - ./app-database:/var/lib/mysql
        ports:
            - '8000:3306'
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'internal-redis:/data'
        networks:
            - internal
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - internal
        ports:
            - 8002:80

